# Package: robo_moveit_config
# Version: 0.0.1
# Description: holds parameters for kinematic solvers
# Maintainer: Casimir Sowinski, "casimirsowinski@gmail.com"
# License: BSD
# Repo: https://github.com/casimirsowinski/robo_hand_01.git
# Author: Casimir Sowinski, "casimirsowinski@gmail.com"
# Year: 2016
head:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
